In [1]:
import numpy as np

In [6]:
def InputParser(file_path: str) -> dict:
    params = dict()
    
    with open(file_path, 'r') as file:
        params['emission'] = file.readline().rstrip()
        _ = file.readline()  # skip '----'
        
        params['emit_dict'] = dict((y, x) for x, y in enumerate(file.readline().rstrip().split()))
        _ = file.readline()  # skip '----'
        
        params['status_dict'] = dict((y, x) for x, y in enumerate(file.readline().rstrip().split()))
        _ = file.readline()  # skip '----'
        
        _ = file.readline()  # skip header
        params['transition_matrix'] = np.array([
            list(map(float, file.readline().rstrip().split()[1:])) for _ in range(len(params['status_dict']))
        ])
        _ = file.readline()  # skip '----'
        
        _ = file.readline()  # skip header
        params['emission_matrix'] = np.array([
            list(map(float, file.readline().rstrip().split()[1:])) for _ in range(len(params['status_dict']))
        ])
    
    return params

In [7]:
test_params = InputParser('test_datasets/testdata_ba10d.txt')
print(test_params['emission'])
print(test_params['emit_dict'])
print(test_params['status_dict'])
print(test_params['transition_matrix'])
print(test_params['emission_matrix'])

xzyyzzyzyy
{'x': 0, 'y': 1, 'z': 2}
{'A': 0, 'B': 1}
[[0.303 0.697]
 [0.831 0.169]]
[[0.533 0.065 0.402]
 [0.342 0.334 0.324]]


In [12]:
import sys
import pandas as pd

arr = np.ones(shape=(3, 3)) / 2
pd.DataFrame(arr).to_csv(sys.stdout, sep='\t', float_format='{:.3g}'.format)

	0	1	2
0	0.5	0.5	0.5
1	0.5	0.5	0.5
2	0.5	0.5	0.5
